# DataSource Settings for Spring Data JPA
# spring.datasource.driver-class-name=
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.auto-commit=false

spring.jpa.show-sql=true
# ddl-auto = update the database schema will be automatically created (and updated),
spring.jpa.hibernate.ddl-auto=update

# The SQL dialect makes Hibernate generate better SQL for the chosen database
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Config schema init query
# spring.sql.init.platform=mysql
# spring.sql.init.schema-locations=classpath:schema.sql
# spring.sql.init.data-locations=classpath:data.sql